version: '3.8'

services:
  nginx:
    # build:
    #   context: ./nginx
    image: alia012/rest-api-nginx:latest
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - simpleapi
  simpleapi:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: alia012/rest-api-simpleapi:latest
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ConnectionStrings__DefaultConnection: "Server=mysql_A;Port=3306;Database=SimpleApiDb;User=root;Password=my-secret-pw;"
    depends_on:
      - mysql_A
    networks:
      - app-network

  mysql_A:
    image: mysql:8.0
    container_name: mysql_A
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: SimpleApiDb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
